[tool.poetry]
name = "test_first"
version = "8.0.2rc1"
description = "Test First Python Mocking Framework designed especially for TDD"
authors = ["Yoav Kleinberger <haarcuba@gmail.com>"]
license = "MIT"
classifiers = [
        "Programming Language :: Python",
        "Programming Language :: Python :: 3",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Topic :: Software Development :: Testing",
]


[tool.poetry.dependencies]
python = "^3.8"
pytest = "^6.2.5"

[tool.poetry.dev-dependencies]
hypothesis = "^6.24.0"
pytest-asyncio = "^0.16.0"
pytest-cov = "^3.0.0"
ipython = "^7.28.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
